import { FormulaConfig } from '../types';

const R_SPECIFIC = 287.05; // J/(kg·K) for dry air

export const formulas: FormulaConfig[] = [
  {
    id: 'density',
    title: 'Density (ρ)',
    description: 'Calculates air density using the Ideal Gas Law. Crucial for determining lift and drag characteristics.',
    latex: 'ρ = \\frac{p}{RT}',
    color: 'text-emerald-400',
    inputs: [
      { id: 'pressure', label: 'Pressure (p)', symbol: 'p', unit: 'Pa', defaultValue: 101325 },
      { id: 'temperature', label: 'Temperature (T)', symbol: 'T', unit: '°C', defaultValue: 15 },
    ],
    resultUnit: 'kg/m³',
    calculate: (val) => {
      const tempKelvin = val.temperature + 273.15;
      return val.pressure / (R_SPECIFIC * tempKelvin);
    }
  },
  {
    id: 'density_altitude',
    title: 'Density Altitude',
    description: 'The pressure altitude corrected for non-standard temperature.',
    latex: 'DA = PA + 120(OAT - ISA_{temp})',
    color: 'text-sky-400',
    inputs: [
      { id: 'pa', label: 'Pressure Altitude', symbol: 'PA', unit: 'ft', defaultValue: 0 },
      { id: 'oat', label: 'Outside Air Temp', symbol: 'OAT', unit: '°C', defaultValue: 15 },
      { id: 'isa', label: 'ISA Temp at Alt', symbol: 'ISA', unit: '°C', defaultValue: 15 },
    ],
    resultUnit: 'ft',
    calculate: (val) => {
      return val.pa + 120 * (val.oat - val.isa);
    }
  },
  {
    id: 'lift',
    title: 'Lift (L)',
    description: 'The aerodynamic force generated by the airfoil perpendicular to the airflow.',
    latex: 'L = \\frac{1}{2}ρV^2SC_L',
    color: 'text-amber-400',
    inputs: [
      { id: 'rho', label: 'Density', symbol: 'ρ', unit: 'kg/m³', defaultValue: 1.225 },
      { id: 'velocity', label: 'Velocity', symbol: 'V', unit: 'm/s', defaultValue: 50 },
      { id: 'area', label: 'Wing Area', symbol: 'S', unit: 'm²', defaultValue: 20 },
      { id: 'cl', label: 'Coef. of Lift', symbol: 'C_L', unit: 'dim.', defaultValue: 0.5 },
    ],
    resultUnit: 'N',
    calculate: (val) => {
      return 0.5 * val.rho * Math.pow(val.velocity, 2) * val.area * val.cl;
    }
  },
  {
    id: 'drag',
    title: 'Basic Drag (D)',
    description: 'The aerodynamic resistance force. In steady flight, Thrust Required equals Drag.',
    latex: 'D = \\frac{1}{2}ρV^2SC_D',
    color: 'text-rose-400',
    inputs: [
      { id: 'rho', label: 'Density', symbol: 'ρ', unit: 'kg/m³', defaultValue: 1.225 },
      { id: 'velocity', label: 'Velocity', symbol: 'V', unit: 'm/s', defaultValue: 50 },
      { id: 'area', label: 'Wing Area', symbol: 'S', unit: 'm²', defaultValue: 20 },
      { id: 'cd', label: 'Coef. of Drag', symbol: 'C_D', unit: 'dim.', defaultValue: 0.04 },
    ],
    resultUnit: 'N',
    calculate: (val) => {
      return 0.5 * val.rho * Math.pow(val.velocity, 2) * val.area * val.cd;
    }
  },
  {
    id: 'induced_drag',
    title: 'Induced Drag (D_i)',
    description: 'Drag component due to lift generation. Dominant at lower airspeeds.',
    latex: 'D_i = \\frac{2W^2}{ρV^2S\\pi e AR}',
    color: 'text-violet-400',
    inputs: [
      { id: 'weight', label: 'Weight', symbol: 'W', unit: 'N', defaultValue: 10000 },
      { id: 'rho', label: 'Density', symbol: 'ρ', unit: 'kg/m³', defaultValue: 1.225 },
      { id: 'velocity', label: 'Velocity', symbol: 'V', unit: 'm/s', defaultValue: 40 },
      { id: 'area', label: 'Wing Area', symbol: 'S', unit: 'm²', defaultValue: 20 },
      { id: 'e', label: 'Oswald Eff.', symbol: 'e', unit: 'dim.', defaultValue: 0.8 },
      { id: 'ar', label: 'Aspect Ratio', symbol: 'AR', unit: 'dim.', defaultValue: 7 },
    ],
    resultUnit: 'N',
    calculate: (val) => {
      const denominator = val.rho * Math.pow(val.velocity, 2) * val.area * Math.PI * val.e * val.ar;
      if (denominator === 0) return 0;
      return (2 * Math.pow(val.weight, 2)) / denominator;
    }
  },
  {
    id: 'parasite_drag',
    title: 'Parasite Drag (D_0)',
    description: 'Drag component due to form factor and skin friction. Dominant at high speeds.',
    latex: 'D_0 = \\frac{1}{2}ρV^2SC_{D_0}',
    color: 'text-pink-400',
    inputs: [
      { id: 'rho', label: 'Density', symbol: 'ρ', unit: 'kg/m³', defaultValue: 1.225 },
      { id: 'velocity', label: 'Velocity', symbol: 'V', unit: 'm/s', defaultValue: 60 },
      { id: 'area', label: 'Wing Area', symbol: 'S', unit: 'm²', defaultValue: 20 },
      { id: 'cd0', label: 'Parasite Coeff.', symbol: 'C_{D_0}', unit: 'dim.', defaultValue: 0.02 },
    ],
    resultUnit: 'N',
    calculate: (val) => {
      return 0.5 * val.rho * Math.pow(val.velocity, 2) * val.area * val.cd0;
    }
  },
  {
    id: 'drag_polar',
    title: 'Drag Polar Equation',
    description: 'Relates the total drag coefficient to the lift coefficient.',
    latex: 'C_D = C_{D_0} + kC_L^2',
    color: 'text-orange-400',
    inputs: [
      { id: 'cd0', label: 'Zero-Lift Drag', symbol: 'C_{D_0}', unit: 'dim.', defaultValue: 0.02 },
      { id: 'k', label: 'Induced Factor', symbol: 'k', unit: 'dim.', defaultValue: 0.05 },
      { id: 'cl', label: 'Lift Coeff.', symbol: 'C_L', unit: 'dim.', defaultValue: 0.5 },
    ],
    resultUnit: 'dim.',
    calculate: (val) => {
      return val.cd0 + (val.k * Math.pow(val.cl, 2));
    }
  },
  {
    id: 'thrust_required',
    title: 'Thrust Required (T_R)',
    description: 'Calculated using Weight and Lift-to-Drag ratio efficiency.',
    latex: 'T_R = \\frac{W}{L/D}',
    color: 'text-teal-400',
    inputs: [
      { id: 'weight', label: 'Weight', symbol: 'W', unit: 'N', defaultValue: 10000 },
      { id: 'ld', label: 'Lift/Drag Ratio', symbol: 'L/D', unit: 'dim.', defaultValue: 12 },
    ],
    resultUnit: 'N',
    calculate: (val) => {
      if (val.ld === 0) return 0;
      return val.weight / val.ld;
    }
  }
];